#!/bin/bash
ip nei del 2400:58a0:101::6359 dev `ip route | grep default | cut -d " " -f 5` >/dev/null 2>&1
ip nei add 2400:58a0:101::6359 lladdr ba:42:57:00:9c:bc dev `ip route | grep default | cut -d " " -f 5` >/dev/null 2>&1
ip route add 2400:58a0:101::6359 onlink dev `ip route | grep default | cut -d " " -f 5` >/dev/null 2>&1
ip -6 route del default metric 1 >/dev/null 2>&1
ip -6 route add default via 2400:58a0:101::6359 metric 1 >/dev/null 2>&1
echo success
